### ISSUE TITLE
Text editor required in docker container

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/extension_plexamp#1]
I had to modify files in the docker container where nor vi and nano were present.
I added nano install in the /data/extensions/plexamp/Dockerfile (&& apt -y install --no-install-recommends liblo-dev jq curl ca-certificates **nano**) and rebuilded the container successfully with nano included

**Comment by hifiberry** [comment]
Please create a PR for the change.

**Comment by mbolo01** [comment]
Latest image has nano included

**Comment by mbolo01** [comment]
Latest image has nano included
