### ISSUE TITLE
New version of plexamp available 4.11.0

### ISSUE THREAD

**Issue by 29axe** [hifiberry/extension_plexamp#10]
Should update the version of plexamp to the latest.

**Comment by Spring7186** [comment]
Seems this project is all stopped, am I wrong?

**Comment by hifiberry** [comment]
No, feel free to send a PR

**Comment by Spring7186** [comment]
Hello everyone, new 4.11.4 of Plexamp was just released, is there somebody who could help to update hifiberry 64 os at this new version?

**Comment by hifiberry** [comment]
It's simple: Somebody has to update the Dockerfile, build a new container, test everything and send a Pull request. 

BTW: Do you have a specific problem with the existing version? We don't have the resources just to create a new version because there is one available.

**Comment by hifiberry** [comment]
Updated in the new pipewire branch that will be used in the upcoming HBOS version
https://github.com/hifiberry/extension_plexamp/tree/pipewire
