### ISSUE TITLE
Plexamp not starting after a container restart

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/extension_plexamp#2]
I found that Plexamp (/app/plexamp/js/index.js) is launched with the container root account during container start and Plexamp key files such as the claim token are stored in the /root directory.
When updating HBOS, Plexamp container is recreated, including the /root directory.
As key Plexamp files are no longer present in the /root directory, Plexamp start is then considered as a very first start that triggers the claim token process which requires a manual step to get and apply the token, thus failing to properly start Plexamp automatically.
Other side effect is that the Plexamp log files are not a accessible from the parent host as the /root dir that contains the logs is not linked to a host directory.

To circumvent this issue, once container has been built and started the first time:

1. Open a bash in the plexamp container as plexamp user: docker exec -it -u 2000 plexampextension /bin/bash
2. from /app/plexamp directory launch Plexamp to claim token (node js/index.js) and follow the instructions
3. restart plexamp container

**Comment by hifiberry** [comment]
The key has to reside in a directory that's mapped to the outside of the container. That would be /home/plexamp
Make sure to store the key in this directory.

**Comment by hifiberry** [comment]
I also recommend adding a PR for documentation how to retrieve the claim token and how to add it to the container.

**Comment by hifiberry** [comment]
@mbolo01 As you seem to know this well: Can you create some documentation how to get the claim token and how to add it to the container?

**Comment by mbolo01** [comment]
@hifiberry where shall I create it? You asked me while ago to create PR but I am not able to do so apparently as  there is only one branch (remember, I'm just a super-user, not a coder, nor a GitHub contributor, nor a Unix expert)

**Comment by pinballpower** [comment]
Just click on edit on the README: https://github.com/hifiberry/extension_plexamp/blob/master/README.md

Github will directly handle forking and creating a PR then.

**Comment by hifiberry** [comment]
Just click on edit on the README: https://github.com/hifiberry/extension_plexamp/blob/master/README.md

Github will directly handle forking and creating a PR then.

**Comment by hifiberry** [comment]
Once I understand this, I can test the changes for the 2 bugs here.

**Comment by mbolo01** [comment]
Before I attempt to write a documentation, please note the following.
In order to use Plexamp, you need a Plex Media Server with some music files in it, or a Tidal account, a Plex Account and preferably a Plex Pass.
The current way I  know to claim token is very manual:
(1) You must install/start Plexamp successfully the very first time, i.e. starting the extension that ultimately includes the "node js/index.js" command which effectively starts Plexamp. At this point installation is paused waiting for the token to be entered. Hopefully this is the point the very 1stHBOS UI Plexamp extension installation should reach. But in order to reach this point bug 1 & 2 must be definitively be fixed. Personally, due to the issues I faced, I resumed the Plexamp setup using docker commands v.s. HBOS UI
(2) Now the tricky part .... while initial startup is waiting for the token, I SSH to HBOS, then I open a bash in the Plexamp container as user plexamp. From there I manually run  "node js/index.js" from /app/plexamp. It will then prompt for the token that I'll generate and copy from the Plex web site. You may find more information for developers like you here: https://forums.plex.tv/t/authenticating-with-plex/609370
(3) Once the token is entered, Plexamp should start and I can access the Web UI.
(4) Once Plexamp is confirmed working, Initial setup script that is still waiting for a token must be stopped and plexamp container must be restarted.

Note: The SETUP PLEXAMP button you have coded in the Plexamp extension source UI cannot be used to enter the token, but is useful for users wanting to jump to Plexamp UI from HBOS UI, so I would not remove it, but rename it OPEN PLEXAMP for example.

**Comment by hifiberry** [comment]
Ok, I still don't understand where to get the token from. 
I don't think we will spend time here to implement some specific Plex authentication scheme, but if there is a simple way for a user to get a token, that should be doable.

**Comment by mbolo01** [comment]
To get the token you must go to a Plex URL where the token is generated based on the Plex userid your signed in with. Then you copy the token and paste it in the extension bash window where the initial script is running and waiting for the key to be entered

**Comment by mbolo01** [comment]
I think some have managed to automate this token input process, I’ll dig.
But in the meantime you should fix the two new issues i raised otherwise people could not leverage your extension process

**Comment by hifiberry** [comment]
Automating the token input shouldn't be a big deal. I'll look into this.

**Comment by mbolo01** [comment]
Token from the Plex.tv web site and a player name are the two expected inputs to the first run of index.js
Also, currently upgrades are not managed by the UI but by scripts or manually, I know, not user  friendly for now

**Comment by mbolo01** [comment]
FYI: Plexamp can be controlled via Home Assistant Plex integration (See what is playing including album art, start/stop/volume), maybe a way to get control from HBOS UI?

**Comment by hifiberry** [comment]
Updated in the new pipewire branch that will be used in the upcoming HBOS version
https://github.com/hifiberry/extension_plexamp/tree/pipewire

@mbolo01 While it might be possible to remotely control plexamp, we leave this to potential contributors. This is simply too much effort for too few users for us to work on. However, we're happy to integrate contributions.
