### ISSUE TITLE
Host audio group GID does not match Plexamp container audio group GID

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/extension_plexamp#3]
As reported in HBOS main git page and for the record here until fixed.

In order for the container app to leverage the host audio interface, the container audio group GID must be set to host audio group GID, i.e. 2001

**Comment by hifiberry** [comment]
Please crate a PR for the change.

**Comment by mbolo01** [comment]
I'm a "skilled" user, not a coder familiar with Github, so not familiar with PR, I guess it is the acronym for "Pull Request" ?

That said, the root cause of the issue is a change of the default  "audio" group GID in HBOS 64 which is under your control. So if you plan to keep your change in the future HBOS release, then I guess a PR mus be required, please confirm.

**Comment by hifiberry** [comment]
Yes, it's a Pull request. 

The change of the GID should be doable in the container. No change of the GID in HBOS should be done as this would effect other players too. 

While we can look into this, this probably won't happen soon as getting HBOS64 ready has the highest priority today.

**Comment by mbolo01** [comment]
When trying to write a PR, I receive the following message:
"Choose different branches or forks above to discuss and review changes. "
Looks like there is only one branch here and I have no clue on how to resume from here.
