### ISSUE TITLE
Wrong plexamp UID in Dockerfile

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/extension_plexamp#4]
The following section has:

RUN groupadd -g 2000 plexamp \
  && useradd -g 2000 -u 2002 -s /bin/bash -d /home/plexamp -G audio plexamp

where is should be:

RUN groupadd -g 2000 plexamp \
  && useradd -g 2000 -u **2000** -s /bin/bash -d /home/plexamp -G audio plexamp

Otherwise plexamp cannot create the working directory at first launch, so fail to start and container keep Restarting(1)

**Comment by hifiberry** [comment]
This requires a change in the extension manager that comes with the next HBOS release
