### ISSUE TITLE
Documentation is wrong about stopping/starting extension is wrong

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/extension_plexamp#7]
it states:
/opt/hifiberry/extensions stop plexamp
/opt/hifiberry/extensions start plexamp

where it should be:
/opt/hifiberry/bin/extensions stop plexamp
/opt/hifiberry/bin/extensions start plexamp

NOTE: You have limited time to use the generated Token, worth mentioning it somewhere in the following instruction: "Edit the file /etc/plexamp.token and add the claim token that you can retrieve from https://plex.tv/claim (this requires a PlexAmp subscription)"

**Comment by octapress** [comment]
> where it should be: /opt/hifiberry/extensions**/bin** stop plexamp /opt/hifiberry/extensions**/bin** start plexamp

This doesn't work for me either.
I simply don't have any command "stop plexamp" regardless how I type the location.

Can you be any more specific?

**Comment by sureecato** [comment]
This worked for me:

/opt/hifiberry/bin/extensions stop plexamp
/opt/hifiberry/bin/extensions start plexamp

**Comment by mbolo01** [comment]
@octapress you are correct, my statement had "bin" misplaced, corrected now. 
That said, Hifiberry original documentation is wrong (or was, I haven't checked since a while)

**Comment by sureecato** [comment]
@mbolo01 yes, and thanks for raising the issue, without your initial post I had no idea where to look.

**Comment by hifiberry** [comment]
Fixed in https://github.com/hifiberry/extension_plexamp/commit/ed512be736b046b65b15a4d2d5e79beb4c7628b9
