### ISSUE TITLE
HBOS Sources/Plexamp screen obsolete

### ISSUE THREAD

**Issue by mbolo01** [hifiberry/extension_plexamp#9]
The below screen shows incorrect information as Plexamp initial setup is done following extension installation instructions. 
I would change the button for something like "Open Plexamp" and change the text below the button accordingly.
<img width="737" alt="Capture d’écran 2024-05-24 à 13 54 42" src="https://github.com/hifiberry/extension_plexamp/assets/57586871/19bd130d-a6de-4bf1-9a7b-7104b3eb373d">

**Comment by hifiberry** [comment]
Updated in the new pipewire branch that will be used in the upcoming HBOS version
https://github.com/hifiberry/extension_plexamp/tree/pipewire
